### ISSUE TITLE
Require Bot.js

### ISSUE THREAD

**Issue by aisflat439** [PaulAsjes/BuildingBots#3]
I run node `v7.4.0` on my machine and find that the code 
    `const Bot = require('./Bot');`
fails, but the code
    `const Bot = require('./bot');`
works. I'm too new to node to know if this is related to a change but this also may be helpful in the errata section.

**Comment by PaulAsjes** [comment]
`require` is case sensitive, so you probably had a file named `bot.js` rather than `Bot.js` which is what caused the import to fail.
